<a href="https://colab.research.google.com/github/lcipolina/ML_Fundamentals/blob/main/Copy_of_Exercise_Set_1a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise Set 1a - Python Arrays & DataFrames

Importing required libraries

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns

Create a Numpy array with 1 column and 100 rows. Fill this with some data of random numbers.

You may utilize the random number functions np.random.randn() or np.random.randint() to generate random numbers.

In [ ]:
rand_int = np.random.randint(1,10,(100,1)) # random numpy array of shape (100,1) with rnd integers between (1,10)
print(rand_int)

[[1]
 [4]
 [3]
 [9]
 [2]
 [1]
 [8]
 [4]
 [2]
 [7]
 [2]
 [7]
 [8]
 [3]
 [3]
 [1]
 [8]
 [6]
 [9]
 [7]
 [4]
 [2]
 [7]
 [1]
 [1]
 [5]
 [1]
 [9]
 [2]
 [5]
 [8]
 [9]
 [5]
 [8]
 [7]
 [5]
 [5]
 [2]
 [3]
 [5]
 [5]
 [8]
 [5]
 [6]
 [8]
 [4]
 [8]
 [3]
 [1]
 [7]
 [3]
 [7]
 [9]
 [3]
 [1]
 [7]
 [6]
 [3]
 [1]
 [2]
 [4]
 [3]
 [3]
 [9]
 [4]
 [9]
 [7]
 [6]
 [4]
 [3]
 [5]
 [6]
 [4]
 [6]
 [7]
 [8]
 [5]
 [6]
 [3]
 [9]
 [7]
 [3]
 [4]
 [4]
 [2]
 [4]
 [6]
 [5]
 [8]
 [4]
 [1]
 [1]
 [9]
 [5]
 [7]
 [3]
 [8]
 [3]
 [2]
 [6]]


Convert numpy array into pandas data series

In [ ]:
df = pd.DataFrame(rand_int, columns=['Column1'])
df

Column1
0         1
1         4
2         3
3         9
4         2
..      ...
95        3
96        8
97        3
98        2
99        6

[100 rows x 1 columns]

Create a Numpy array with 3 columns and 100 rows. 
Fill this with some data of random numbers.

In [ ]:
rand_int = np.random.randint(1,10,(100,3)) # random numpy array of shape (100,3) with rnd integers between (1,10)
print(rand_int)

[[1 9 4]
 [6 5 9]
 [2 8 6]
 [1 5 1]
 [9 2 7]
 [5 5 9]
 [8 5 2]
 [7 2 2]
 [2 6 8]
 [8 2 4]
 [3 9 8]
 [4 5 6]
 [5 6 3]
 [6 1 4]
 [9 4 3]
 [3 9 5]
 [6 6 1]
 [3 6 6]
 [4 9 9]
 [1 2 1]
 [1 7 6]
 [5 4 7]
 [4 6 4]
 [5 7 2]
 [2 5 8]
 [6 6 8]
 [7 7 4]
 [4 9 8]
 [9 4 6]
 [1 1 9]
 [8 2 7]
 [9 8 6]
 [4 2 2]
 [4 3 7]
 [8 7 2]
 [6 6 9]
 [9 5 8]
 [2 9 6]
 [6 6 2]
 [1 1 7]
 [2 1 4]
 [7 8 4]
 [7 6 5]
 [1 7 9]
 [4 7 8]
 [1 2 4]
 [8 9 9]
 [3 5 5]
 [2 1 2]
 [1 2 4]
 [6 8 5]
 [2 7 6]
 [1 7 7]
 [9 9 1]
 [9 9 6]
 [5 8 5]
 [7 7 8]
 [5 7 7]
 [2 8 6]
 [3 9 6]
 [1 4 8]
 [9 6 2]
 [8 4 9]
 [8 5 8]
 [4 6 6]
 [6 7 1]
 [5 7 4]
 [9 5 8]
 [8 7 2]
 [4 1 4]
 [4 8 8]
 [9 8 8]
 [2 6 2]
 [2 6 3]
 [8 8 7]
 [9 7 8]
 [3 2 4]
 [9 1 1]
 [8 6 7]
 [9 2 7]
 [9 5 4]
 [8 4 6]
 [5 1 3]
 [7 4 6]
 [6 4 1]
 [9 5 4]
 [6 4 5]
 [6 2 6]
 [3 4 3]
 [1 3 9]
 [2 7 1]
 [6 2 5]
 [9 9 7]
 [8 6 1]
 [1 2 6]
 [5 3 4]
 [9 2 8]
 [2 7 3]
 [3 3 2]
 [6 9 6]]


Convert the above array into a pandas DataFrame. 

Note that a DataFrame has labels for each column. Choose some appropriate labels, such as X1, X2, X3.

In [ ]:
df = pd.DataFrame(rand_int, columns=['X1','X2','X3'])
df

Use the above generated DataFrame to do a pairplot.

Utilize the Seaborn function
sns.pairplot()

In [ ]:
import seaborn as sns
g = sns.pairplot(df)


import matplotlib.pyplot as plt
plt.show()

NameError: ignored


### Report

* We have generated a matrix of random uncorrelated numbers. 

* We then plotted the numbers using the "pairplot()" function from the seaborn package. 


  This function generates a pair-wise plot with one variable on the X axis against the other variable plotted on the Y axis.

  This is a quick way to study the correlation of both variables. Say they are both similar, we would expect to obtain all the dots aligned over the 45 degree line X=Y.

  Here, because we have plotted random numbers, we see that the dots are all over the place, uniformly distributed across the plane.

Note that on the diagonal we have a histogram of each of the variables.

This is a quick way to get a feel of the separability of the behaviour of the data. 